const employeeData = [
  {
    id: 1,
    name: "Anil Kumar",
    email: "anil.kumar@example.com",
    salary: 70000,
    role: "Manager",
    joiningYear: 2019,
  },
  {
    id: 2,
    name: "Divya Reddy",
    email: "divya.reddy@example.com",
    salary: 50000,
    role: "Developer",
    joiningYear: 2020,
  },
  {
    id: 3,
    name: "Ravi Teja",
    email: "ravi.teja@example.com",
    salary: 45000,
    role: "Tester",
    joiningYear: 2021,
  },
  {
    id: 4,
    name: "Suma Rao",
    email: "suma.rao@example.com",
    salary: 52000,
    role: "Developer",
    joiningYear: 2020,
  },
  {
    id: 5,
    name: "Pavan Sai",
    email: "pavan.sai@example.com",
    salary: 30000,
    role: "Trainee",
    joiningYear: 2023,
  },
  {
    id: 6,
    name: "Meena Shah",
    email: "meena.shah@example.com",
    salary: 46000,
    role: "Tester",
    joiningYear: 2021,
  },
  {
    id: 7,
    name: "Karthik Reddy",
    email: "karthik.reddy@example.com",
    salary: 72000,
    role: "Manager",
    joiningYear: 2018,
  },
  {
    id: 8,
    name: "Sneha Iyer",
    email: "sneha.iyer@example.com",
    salary: 51000,
    role: "Developer",
    joiningYear: 2020,
  },
  {
    id: 9,
    name: "Abhinav Singh",
    email: "abhinav.singh@example.com",
    salary: 47000,
    role: "Tester",
    joiningYear: 2021,
  },
  {
    id: 10,
    name: "Lakshmi Devi",
    email: "lakshmi.devi@example.com",
    salary: 29000,
    role: "Trainee",
    joiningYear: 2023,
  },
  {
    id: 11,
    name: "Naveen Patil",
    email: "naveen.patil@example.com",
    salary: 68000,
    role: "Manager",
    joiningYear: 2019,
  },
  {
    id: 12,
    name: "Geetha Ram",
    email: "geetha.ram@example.com",
    salary: 53000,
    role: "Developer",
    joiningYear: 2020,
  },
  {
    id: 13,
    name: "Ajay Kumar",
    email: "ajay.kumar@example.com",
    salary: 44000,
    role: "Tester",
    joiningYear: 2021,
  },
  {
    id: 14,
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    salary: 50000,
    role: "Developer",
    joiningYear: 2022,
  },
  {
    id: 15,
    name: "Rakesh Nair",
    email: "rakesh.nair@example.com",
    salary: 27000,
    role: "Trainee",
    joiningYear: 2023,
  },
  {
    id: 16,
    name: "Tanvi Joshi",
    email: "tanvi.joshi@example.com",
    salary: 48000,
    role: "Tester",
    joiningYear: 2021,
  },
  {
    id: 17,
    name: "Sandeep Rao",
    email: "sandeep.rao@example.com",
    salary: 75000,
    role: "Manager",
    joiningYear: 2018,
  },
  {
    id: 18,
    name: "Neha Verma",
    email: "neha.verma@example.com",
    salary: 55000,
    role: "Developer",
    joiningYear: 2022,
  },
  {
    id: 19,
    name: "Vikram Shetty",
    email: "vikram.shetty@example.com",
    salary: 46000,
    role: "Tester",
    joiningYear: 2021,
  },
  {
    id: 20,
    name: "Shreya Rao",
    email: "shreya.rao@example.com",
    salary: 31000,
    role: "Trainee",
    joiningYear: 2023,
  },
];
export default employeeData;
